package facebook

type GetMakesRequest struct {
	CategoryIDS            []int64          `json:"category_ids"`
	CategoryRankingEnabled bool             `json:"category_ranking_enabled"`
	ContextualData         []ContextualData `json:"contextual_data"`
	HideL2Cats             bool             `json:"hide_l2_cats"`
	SavedSearchQuery       interface{}      `json:"savedSearchQuery"`
	Surface                string           `json:"surface"`
	TopicPageParams        TopicPageParams  `json:"topicPageParams"`
	VirtualCategoryIDS     []interface{}    `json:"virtual_category_ids"`
}

type AutoGenerated struct {
	BuyLocation struct {
		Latitude  float64 `json:"latitude"`
		Longitude float64 `json:"longitude"`
	} `json:"buyLocation"`
	CategoryIds            []interface{} `json:"category_ids"`
	CategoryRankingEnabled bool          `json:"category_ranking_enabled"`
	ContextualData         []struct {
		Name  string `json:"name"`
		Value string `json:"value"`
	} `json:"contextual_data"`
	HideL2Cats       bool        `json:"hide_l2_cats"`
	SavedSearchQuery interface{} `json:"savedSearchQuery"`
	Surface          string      `json:"surface"`
	TopicPageParams  struct {
		LocationID string `json:"location_id"`
		URL        string `json:"url"`
	} `json:"topicPageParams"`
	VirtualCategoryIds []interface{} `json:"virtual_category_ids"`
}

type GetMakesResponse struct {
	Data struct {
		Viewer struct {
			MarketplaceStructuredFields []struct {
				Typename                     string `json:"__typename"`
				FilterType                   string `json:"filter_type"`
				FilterKey                    string `json:"filter_key"`
				ShouldRenderAsSubFilter      bool   `json:"should_render_as_sub_filter"`
				IsMarketplaceStructuredField string `json:"__isMarketplaceStructuredField"`
				DisplayName                  string `json:"display_name"`
				Choices                      []struct {
					DisplayName           string      `json:"display_name"`
					Value                 string      `json:"value"`
					Active                interface{} `json:"active"`
					SeoNavigableFilters   interface{} `json:"seo_navigable_filters"`
					Slug                  interface{} `json:"slug"`
					VirtualAttributeValue interface{} `json:"virtual_attribute_value"`
					ContextualFilters     interface{} `json:"contextual_filters"`
				} `json:"choices"`
				FieldKey     string        `json:"field_key"`
				ChildFilters []interface{} `json:"child_filters"`
				ClearFields  interface{}   `json:"clear_fields"`
				Range        interface{}   `json:"range"`
			} `json:"marketplace_structured_fields"`
		} `json:"viewer"`
	} `json:"data"`
}
